### ISSUE TITLE
Test various accessibility fixes

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-rhythm#14]
These are the main things we're checking Rhythm for:

- [x] Text contrast throughout the site on each of the stylesheets
- [x] Item links on item/browse no longer have separate text and image links: they are consolidated to a single link to an item/show.
- [x] Site uses appropriate heading levels.

Please run the theme through our accessibility auditors: axeDevtools, lighthouse, and WAVE.

**Comment by katknow** [comment]
Regarding color contrast:
- devAxe tools is pinging just about everything on the homepage across style sheets, but it seems the margin is about .3 (for instance, it says the threshold is 6.8 but recommends 7.2). The featured boxes on browse pages also get pinged.
- Lighthouse gives Spring Rhythm a 100% accessibility score across pages. It pings all the "featured" boxes on the homepage and browse page for Rhythm and Blue and Fall Rhythm.
- WAVE is marking all text in in "featured collection" as too low contrast on Fall Rhythm but everything else is fine for that style sheet. For Rhythm and Blue, it is pinging h3 on item pages, all the sorting option links on browse pages, and the titles of featured items/exhibits/collections on the homepage. Spring Rhythm is getting a message for the titles under "recently added items" on the homepage and all the blue-green text on the browse pages (sorting links, titles, etc).

In terms of headings, nothing is getting highlighted as an issue in any of the tools. No links are being referred to by any of the accessibility checkers other than the color contrast issues so I guess those are good to go too!

**Comment by kimisgold** [comment]
I think I've gotten all the homepage and featured asides in Rhythm and Blue and Fall now. (https://github.com/omeka/theme-rhythm/commit/0c7795f8a17b36d4caa834d54defb426cf722cf0) Let me know if there's anything I've missed.

**Comment by katknow** [comment]
Okay, so the homepage and featured asides for both those style sheets are passing in both WAVE and Lighthouse. devAxe tools is being a little more finicky, so I've included the screenshots below so you can decide if you want to keep working with them or not.

For Fall:

![devAxe Fall Featured Collection](https://github.com/omeka/theme-rhythm/assets/84726696/40371f39-450e-4061-ab90-f217e79d388e)

![devAxe Fall View All Items](https://github.com/omeka/theme-rhythm/assets/84726696/62106e9d-72b9-4fe0-902a-3ac1306c6720)

For Rhythm and Blue:

![devAxe Blue Featured Item](https://github.com/omeka/theme-rhythm/assets/84726696/7fe8ac69-a878-4198-aca0-9cd50437913e)

![devAxe Blue featured collection](https://github.com/omeka/theme-rhythm/assets/84726696/b2ac50a7-a234-43b6-99f2-3273c987ff20)

![devAxe Blue Featured Exhibit](https://github.com/omeka/theme-rhythm/assets/84726696/2ec57784-4f2f-4882-b5c0-0e836064cce8)

![devAxe Blue View All Items](https://github.com/omeka/theme-rhythm/assets/84726696/a922b62a-73a1-45c1-a7e2-f3d8ccc0cb9b)

**Comment by kimisgold** [comment]
@katknow Just confirming: after reinstalling axe devtools, were you able to find any other issues here?

**Comment by katknow** [comment]
@kimisgold its recording zero issues after the reinstall, so I think we're good to go!
