### ISSUE TITLE
"Browse Collections" view is missing the word "Browse" in its title

### ISSUE THREAD

**Issue by JonathanReeve** [omeka/theme-rhythm#2]
I'm not 100% sure this is a problem with the theme. The "Browse Exhibits" view has a header that says "Browse Exhibits"; the "Browse Items" view has a header that says "Browse Items," however the "Browse Collections" view has a header that simply says "Collections."

**Comment by JonathanReeve** [comment]
As in: http://aphdigital.org/GVH/collections

Strangely, though, in my forked version of the above page, this doesn't seem to be happening. 

I also noticed that the rhythm theme doesn't have a /collections folder, so this is probably not a problem with the theme.

**Comment by kimisgold** [comment]
Fixed in update to responsive styles.
