### ISSUE TITLE
Image thumbnail for "featured item" overflows if not a square thumbnail

### ISSUE THREAD

**Issue by JonathanReeve** [omeka/theme-rhythm#3]
It looks like the function item_has_thumbnail checks for derivative images, but, as far as I can tell, doesn't differentiate between a square thumbnail and a differently-sized derivative image. 

A possible fix would be to have this function somehow make sure that the thumbnail is a square thumbnail of a certain size, so that it doesn't try to fit a large image into an otherwise small space. 

Another fix might be to force a client-side resize in the browser by changing the image properties in CSS?

**Comment by zerocrates** [comment]
All images that have thumbnails also have square thumbnails. I'm not sure of the context here, but you can always choose which kind of thumbnail to display. As I remember, Rhythm uses the square thumbnails when displaying the featured item.

**Comment by JonathanReeve** [comment]
If you check out the way the Featured Item box looks on this site: http://aphdigital.org/GVH/items and reload the page a bunch of times, sometimes a thumbnail is displayed there which overflows from the page completely. I think this is because the administrators of GVH ran the Image Resize plugin at different times with different values--it looks like there are 400x400 thumbnails in archive/square_thumbnails, but also 300x300 and 200x200 thumbnails. The 200x200 ones are displaying OK, but the 400x400 ones are overflowing. To correct this issue, I tried adding some CSS to resize 400px images down to 200px, so as to prevent the overflow. This might be a little kludgey--I don't know how this sort of thing impacts performance--but it might work.

**Comment by zerocrates** [comment]
Ah, OK.

Yes, the theme helpers really don't concern themselves with the actual size of the images they're displaying, the assumption is that the thumbnails have been generated at whatever the size the site admins want is. I don't think we'll be likely to change this, but some themes (maybe including Rhythm?) do have some CSS size constraints on images.

I think the more likely scenario is that the thumbnail constraints were changed a few times, but the Image Resize plugin wasn't run. I'm not _too_ familiar with it, but I believe the way it works, all the thumbnails would be the same size when it's done.

Using Image Resize to get all the thumbnails the same size is probably the nicest way to deal with this, but CSS max-width or whatever would be fine too, I'd think.

**Comment by JonathanReeve** [comment]
Cool. Here's my fix: https://github.com/JonathanReeve/theme-rhythm/commit/076b80352557338f68e0eb3ae8c5a5d18b838900

It also centers the thumbnails a little better with 20px left margins instead of 65px. 

I'll try submitting a pull request.

**Comment by kimisgold** [comment]
Fixed in update to responsive styles.
