### ISSUE TITLE
Broken style seemingly as a result of new compilation

### ISSUE THREAD

**Issue by kalbers** [omeka/theme-rhythm#7]
200+% seems a touch high

https://github.com/omeka/theme-rhythm/blame/master/css/style.css#L1586

**Comment by kimisgold** [comment]
@kalbers This should now be fixed in 2ec88762b39a57d3c6164447f2a6bf83f1fd7e4a. Can you pull and test that the widths look right?

**Comment by kalbers** [comment]
Looks correct now.
